---
- name: Create Base Ubuntu VM on Proxmox
  hosts: proxmox
  become: true
  tasks:
    - name: Upload the create-base-template script
      ansible.builtin.copy:
        src: ./scripts/create-ubuntu-base-template.sh
        dest: /root/create-ubuntu-base-template.sh
        mode: '0755'

    - name: Execute the script if not already done
      ansible.builtin.command: /root/create-ubuntu-base-template.sh
      args:
        creates: /root/.template_initialized
