---


- name: Install and configure Tailscale
  hosts: tailscale
  become: true

  tasks:
    - name: Install dependencies
      apt:
        name: curl
        state: present
        update_cache: true

    - name: Install Tailscale
      shell: curl -fsSL https://tailscale.com/install.sh | sh

    - name: Authenticate to Tailscale
      shell: |
        tailscale up --authkey {{ tailscale_authkey }}
      args:
        creates: /var/lib/tailscale/tailscaled.state
