---
- name: Configure Tailscale Node
  hosts: tailscale
  become: true
  vars_files:
    - vars/secrets.yml  # Bevat jouw tailscale_authkey via Ansible Vault

  tasks:
    - name: Ensure SSH directory exists
      ansible.builtin.file:
        path: /home/ubuntu/.ssh
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Upload authorized SSH key
      ansible.builtin.copy:
        src: ~/.ssh/id_rsa.pub
        dest: /home/ubuntu/.ssh/authorized_keys
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present
        update_cache: true

    - name: Download Tailscale GPG key
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/jammy.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: '0644'

    - name: Add Tailscale apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu jammy main"
        state: present
        filename: tailscale

    - name: Update apt cache after adding Tailscale repo
      ansible.builtin.apt:
        update_cache: true

    - name: Install Tailscale package
      ansible.builtin.apt:
        name: tailscale
        state: present

    - name: Connect to Tailscale using AuthKey
      ansible.builtin.shell: |
        set -o pipefail
        tailscale up --authkey {{ tailscale_authkey }}
      args:
        executable: /bin/bash
        creates: /var/lib/tailscale/tailscaled.state
