---
- name: Create Base Ubuntu VM on Proxmox
  hosts: proxmox
  become: yes
  tasks:
    - name: Upload the create-base-template script
      copy:
        src: ./create-ubuntu-base-template.sh
        dest: /root/create-ubuntu-base-template.sh
        mode: '0755'

    - name: Execute the script
      command: /root/create-ubuntu-base-template.sh
